# Generated by Django 4.2.7 on 2025-03-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0050_remove_conversationmessage_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='user_name',
        ),
    ]
